### PR TITLE
fix: ou can open in new tab

### PR DESCRIPTION
**Pull request by fannydufresne**

### CODE REVIEW

**Comment by ashikzk** [comment]
@fannydufresne Please provide description of what change was made and why.

**Comment by fannydufresne** [comment]
Allows to open elements of the left menu in new tabs (right click / ctrl click)

**Comment by ashikzk** [comment]
@fannydufresne Still confused why do we need this. Can you please mention the OU task ID or the task link? That should help in explanation. Also, please edit the description of the PR and add description as well as the OU task link.

**Comment by fannydufresne** [comment]
@ashikzk I claimed and submitted the task on open united, so it "disappeared"'

**Comment by ashikzk** [comment]
@fannydufresne I have found the associated task and reviewed your PR. Looks good. Thanks for your contribution.

**Pull request merged**
