### PR TITLE
file uploader 

### PR DESCRIPTION
**Pull request by devsugun**
drag and drop feature into description[https://github.com/devsugun/product-factory-frontend/blob/main/components/FileUploader/index.tsx](url)

### CODE REVIEW

**Comment by ashikzk** [comment]
@devsugun Can you please explain what is the purpose of the file uploaded and remove task that you have added? Besides, there is no "claimedBy" property in the task object. Why that field is being used? If you read the file carefully, you will see that the assigned person's info is already being shown in the page and there is absolute no need to make any change to this file.

**Comment by devsugun** [comment]
The remove task is the previous project given to me by farboid. Some one
has claimed it so he gave me another task. So i am still working on it. I
make PR for 2 projects.
One is file uploader a task made by farboid
To drag and drop file to project description in frontend.
The backend is the npm package which will make it work and installed in the
package.json.

And the second one is the claimed by field which should show the user who
claimed the task. I have created this field in the frontend and tried to
declare its function in the backend.

**Comment by ashikzk** [comment]
@devsugun Please open a separate PR for the other task and include a link to that task in the description so that I can evaluate that.
As for the claim task, as I have said, there is no need to add a new claimed by field. The front-end already shows who has claimed the task. That piece of info comes with the task details. Please try to carefully check the existing data models and then make any change if needed instead of adding unnecessary fields.

**Comment by ashikzk** [comment]
Please use one PR for a single task.

**Comment by devsugun** [comment]
Ok will do that thanks.

**Pull request closed without merging**
